import streamlit as st

st.title('Azalpenak')
st.header('Zer aztertu')
st.markdown("- Tendentzia")
st.markdown("- Bolatilitatea")
st.markdown("- Bolumena")
st.markdown("- Broquer")
st.markdown("- Divisas i impuestos")

st.header('SMA eta EMA')

st.header('Candle')
st.markdown('Irakurtzeko: https://www.investopedia.com/trading/candlestick-charting-what-is-it/')
st.markdown('- Candlesticks are useful when trading as they show four price points (open, close,')
st.markdown('      high, and low) throughout the period the trader specifies.')
st.image('candlestick.png',width=500)

st.header('Bollinger')
st.text('Irakurtzeko: https://www.investopedia.com/terms/b/bollingerbands.asp')
st.write('It helps gauge the volatility of stocks and other securities to determine if they are over- or undervalued')
st.markdown('- The bands widen when a stock\'s price becomes more volatile and contract when it is more stable.')
st.markdown('- Many traders see stocks as overbought as their price nears the upper band')
st.markdown('- and oversold as they approach the lower band, signaling an opportune time to trade.')

st.header('MDCD')
st.text('Irakurtzeko: https://www.investopedia.com/articles/forex/05/macddiverge.asp')
st.write('Two lines: MACD and signal line.')
st.write('The MACD histogram is a visual representation of the difference between the MACD and the signal line')
st.write('The histogram is positive when the MACD is above its nine-day EMA and negative when the MACD is below its nine-day EMA.')
st.write(' The point on the histogram where momentum is zero is the zero line. ')
st.write('If prices change rapidly, the histogram bars grow longer as the speed of the price')
st.write('movement—its momentum—accelerates and shrinks as price movement decelerates. ')
st.write('A crossover occurs when the signal and MACD line cross each other.')
st.markdown('- Bullish (erosi) signal when MACD line moves above the signal line')
st.markdown('- MACD triggers a sell signal (bearish) when it moves below its nine-day EMA. ')
st.markdown('- When the MACD crosses from below to above the zero line, it is considered a bullish signal (erosi).')
st.markdown('- If it crosses from above to below the zero line, it is considered a bearish signal (saldu)')

st.header('RSI')
st.write('The relative strength index (RSI) signals whether a market is considered overbought or oversold to recent price levels.')
st.write('The default period is 14 periods with values bounded from 0 to 100.')
st.markdown('- A value above 70 suggests an overbought condition')
st.markdown('- A value below 30 is considered oversold')
st.write('MACD measures the relationship between two EMAs, while the RSI measures price change to recent price highs and lows.')
st.write('These indicators are used together to give analysts a more complete technical picture.')

st.header('ADX')
st.markdown("- The average directional index (ADX) is a technical indicator used by traders to determine the strength of a price trend")
st.markdown("- Many traders will use ADX readings above 25 to suggest that the trend is strong enough (either upwards o downwards) for trend-trading strategies,")
st.latex("\t 0-25: Absent or Weak Trend; 25-50: Strong Trend; 50-75: Very Strong Trend; 75-100: Extremely Strong Trend")
st.text("The direction of the ADX line is important for reading trend strength. When the ADX line is rising, trend strength")
st.text("is increasing, and the price moves in the direction of the trend. When the line is falling, trend strength is decreasing,")
st.text("and the price enters a period of retracement or consolidation. ")

st.header('Volume')
st.markdown("- Irakurtzeko: https://www.investopedia.com/terms/v/volumeoftrade.asp")
st.markdown("- Edo hau:https://www.investopedia.com/articles/technical/02/010702.asp")
st.markdown("- Volume measures the number of shares traded in a stock.")
st.markdown("- Volume can indicate market strength, as rising markets on increasing volume are viewed as strong and healthy.")
st.markdown("- When prices fall on increasing volume, the trend is gathering strength to the downside.")
st.markdown("- When prices reach new highs (or no lows) on decreasing volume, watch out—a reversal might be taking shape.")

st.header('VPT')
st.text('Irakurtzeko:')
st.markdown('- https://www.investopedia.com/terms/v/vptindicator.asp')
st.markdown('- https://www.investopedia.com/ask/answers/030315/what-volume-price-trend-indicator-vpt-formula-and-how-it-calculated.asp')
st.write('The volume price trend (VPT) indicator helps determine a security’s price direction and strength of price change.')
st.write('The indicator consists of a cumulative volume line that adds or subtracts a multiple of the percentage change')
st.write('in a share price’s trend and current volume, depending upon the security’s upward or downward movements. ')
st.write('As a technical momentum indicator, VPT allows traders and analysts to identify the supply and demand parity of a stock')
st.write('The VPT indicator can be used in conjunction with moving averages and the average directional index (ADX) to confirm trending markets.')
st.write('a trader could buy when the ADX is above 25, and the VPT line is above its signal line. They could sell when the ADX has a value below 25,')
st.write('and the VPT line is below its signal line')